[general]
import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
